Cleanup
keithb418/scrum-team-app pull request #108
Opened 2018-04-02 03:39 UTC by Crunchwrap78

Things to note.
- eslint needs to be updated for es6/es7 syntax in classes
- vendor file before compression is still big in size. vendor compressed resizes well, only thing is the size is still pushing the limit recommended
- dependencies were updated in the process.
- I'll be leaving comments with explanations on changes for clarity

2018-04-03 03:23 UTC, Crunchwrap78 commented on .babelrc
> +  ],
these plugins allow for us to use 
1) arrow functions for functions, so no more setting the context of this. 
2) spread operator, so you use the spread syntax in our classes
3) dynamic imports, so you can now dynamically import dependencies instead of how we module import them in each file. to note this is used for code splitting
4) transform runtime is optional, but references all the helpers babel uses reducing duplicate helpers.

2018-04-14 13:39 UTC, keithb418 commented on front-end/src/actions/fetch.js
> +    error: "An error has occur"
Typo: An error has occurred

2018-04-14 13:42 UTC, keithb418 commented on front-end/src/actions/shared.js
> +    Promise.all([API.getRoles(), API.getTeams(), API.getTeamMemebers()])
typo: getTeamMembers

2018-04-14 13:43 UTC, keithb418 commented on front-end/src/actions/shared.js
> +   Promise.all([API.getTeamMemeber(id), API.getTeams()])
Typo: getTeamMember

2018-04-14 13:44 UTC, keithb418 commented on front-end/src/actions/teamMembers.js
> +	API.getTeamMemeber(id)
typo: getTeamMember

2018-04-14 13:46 UTC, keithb418 commented on front-end/src/actions/teamMembers.js
> +export const createTeamMember = (teamMember) => (dispatch) => {
Rename to handleCreateTeamMember for consistency with handleFetchTeamMember.  It'll show the difference between the redux action to be dispatched and the function to be called which actually makes the request to the API.

2018-04-14 13:47 UTC, keithb418 commented on front-end/src/actions/teamMembers.js
> +export const hanldeUpdateTeamMember = (teamMember) => (dispatch) => {
typo: handleUpdateTeamMember

2018-04-14 13:47 UTC, keithb418 commented on front-end/src/actions/teamMembers.js
> +	API.deleteTeamMemebers(id)
typo: deleteTeamMembers

2018-04-14 13:48 UTC, keithb418 commented on front-end/src/actions/teamMembers.js
> +export const deleteTeamMember = (id) => (dispatch) => {
Update to handleDeleteTeamMember for consistency.

2018-04-14 13:48 UTC, keithb418 commented on front-end/src/actions/teamMembers.js
> +export const changeTeam = (_id, team) => (dispatch) => {
update to handleChangeTeam for consistency

2018-04-14 13:52 UTC, keithb418 commented on front-end/src/actions/teams.js
> +export const deleteTeam = id => dispatch => {
rename to handleDeleteTeam for consistency

2018-04-14 13:53 UTC, keithb418 commented on front-end/src/actions/teams.js
> +export const updateTeam = (team) => dispatch => {
rename to handleUpdateTeam for consistency

2018-04-14 13:53 UTC, keithb418 commented on front-end/src/actions/teams.js
> +export const createTeam = team => dispatch =>{
change to handleCreateTeam for consistency

2018-04-14 13:54 UTC, keithb418 commented on front-end/src/components/App.js
> +const TeamsColumns = (props) => (
Each of these components should be separated into its own file.

2018-04-14 13:56 UTC, keithb418 commented on front-end/src/components/Loading.js
> +const Loading = (props) => {
We can remove props if it's not needed.

2018-04-14 14:26 UTC, keithb418 commented on front-end/src/utils/api.js
> +    getTeamMemeber (id) {
typo: getTeamMember

2018-04-14 14:26 UTC, keithb418 commented on front-end/src/utils/api.js
> +    getTeamMemebers () {
typo: getTeamMembers

2018-04-14 14:26 UTC, keithb418 commented on front-end/src/utils/api.js
> +    deleteTeamMemebers (id) {
typo: deleteTeamMembers

2018-04-14 14:36 UTC, keithb418 requested changes
In general, it looks good.  Overall some feedback:

1. Watch the typos, I found several
2. We should keep components in separate files, I noticed we had a whole bunch of dynamic loader components in App.js, if possible we should have them in separate files, it would be easier to maintain
3. There should be some sort of differentiation between the actions that you just dispatch to update the store, and the actions that actually interact with the API.  I put down some possibilities, but feel free to come up with your own solution.

And a couple clarifying questions (just out of curiosity):

1. Why was React Router removed?
2. What is the purpose of the StateLoader / why are we saving things to localStorage?

2018-04-14 15:15 UTC, Crunchwrap78 commented
@keithb418 
1) will fix
2) I addressed this in the comments
3) will fix

other questions
1) I thought I posted that comment but I guess not. react-router-redux  is unnecessary in react-router-dom since it internally handles your history. if you were using the older version before version 4 then yes you would need it.
2) In redux your store is never persisted so you always have to reload your data. There are other remedies to solve this in react like graphql + apollo or relay to bind the data to components. This will speed up performance in loading our app from different views since our props are always persisted. I will note I'm not a complete expert at this seeing as my state structure is pretty basic, but I understand the logistics of it. In general we should only use the data needed in our components, but I added everything in state since in the future the structure will change. I haven't seen any articles that have said you shouldn't do this and actually some encouraged it. You can actually view twitter's state in the local storage

2018-04-15 12:48 UTC, asc2683 commented
This is more of a general comment to do with project branch naming conventions. Since this is more of a major refactoring task, perhaps consider naming the branch as refactor/release-1.1

See contributing doc for branch naming convention: https://github.com/keithb418/scrum-team-app/blob/development/CONTRIBUTING.md

Also, for future refactoring, breaking the refactoring to small tasks into specific modules or functionality (i.e., webpact, react-router, or redux state manegement) would be helpful.

2018-04-15 18:28 UTC, Crunchwrap78 commented
@asc2683 The react-router and webpack refactor went hand in hand with the dynamic imports. The only thing that should have been separated was the redux state management. After this merges I'll get started on unit tests

2018-04-21 23:09 UTC, keithb418 approved these changes

2018-04-22 09:49 UTC, merged